### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by doggy30** [ryan9918/adidas-account-gen#3]
hello, i don't know why i have this error, you can tell me ?
![python](https://user-images.githubusercontent.com/26242792/31919197-0c697f8a-b861-11e7-8b72-fdef09cdbee7.JPG)

**Comment by ChrisPotts** [comment]
Change _thread to thread in the python file

**Comment by ryan9918** [comment]
make sure you are using the correct version of python as stated in the readme
