### ISSUE TITLE
mac issue

### ISSUE THREAD

**Issue by Gamunji** [ryan9918/adidas-account-gen#5]
<img width="596" alt="screen shot 2018-01-20 at 12 08 39 pm" src="https://user-images.githubusercontent.com/35634456/35185991-d826aa4e-fdda-11e7-8efe-5cc4bcbafd15.png">

**Comment by ryan9918** [comment]
Thanks for alerting me to this. I had made a mistake in the error handling that I did not realise during my own testing as I am a windows user. It has now been fixed with the latest commit.
